package entities;
// Generated Jun 5, 2017 11:37:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Loaisanpham generated by hbm2java
 */
public class Loaisanpham  implements java.io.Serializable {


     private int id;
     private String loaiSanPham;
     private Set sanphams = new HashSet(0);

    public Loaisanpham() {
    }

	
    public Loaisanpham(int id) {
        this.id = id;
    }
    public Loaisanpham(int id, String loaiSanPham, Set sanphams) {
       this.id = id;
       this.loaiSanPham = loaiSanPham;
       this.sanphams = sanphams;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLoaiSanPham() {
        return this.loaiSanPham;
    }
    
    public void setLoaiSanPham(String loaiSanPham) {
        this.loaiSanPham = loaiSanPham;
    }
    public Set getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set sanphams) {
        this.sanphams = sanphams;
    }




}


