package entities;
// Generated Jun 5, 2017 11:37:11 PM by Hibernate Tools 4.3.1



/**
 * Sanpham generated by hbm2java
 */

public class Sanpham  implements java.io.Serializable {


     private String maSanPham;
     private Loaisanpham loaisanpham;
     private String tenSanPham;
     private String gia;
     private Integer soLuongTonKho;

    public Sanpham() {
    }

	
    public Sanpham(String maSanPham) {
        this.maSanPham = maSanPham;
    }
    public Sanpham(String maSanPham, Loaisanpham loaisanpham, String tenSanPham, String gia, Integer soLuongTonKho) {
       this.maSanPham = maSanPham;
       this.loaisanpham = loaisanpham;
       this.tenSanPham = tenSanPham;
       this.gia = gia;
       this.soLuongTonKho = soLuongTonKho;
    }
   
    public String getMaSanPham() {
        return this.maSanPham;
    }
    
    public void setMaSanPham(String maSanPham) {
        this.maSanPham = maSanPham;
    }
    public Loaisanpham getLoaisanpham() {
        return this.loaisanpham;
    }
    
    public void setLoaisanpham(Loaisanpham loaisanpham) {
        this.loaisanpham = loaisanpham;
    }
    public String getTenSanPham() {
        return this.tenSanPham;
    }
    
    public void setTenSanPham(String tenSanPham) {
        this.tenSanPham = tenSanPham;
    }
    public String getGia() {
        return this.gia;
    }
    
    public void setGia(String gia) {
        this.gia = gia;
    }
    public Integer getSoLuongTonKho() {
        return this.soLuongTonKho;
    }
    
    public void setSoLuongTonKho(Integer soLuongTonKho) {
        this.soLuongTonKho = soLuongTonKho;
    }




}


