package entities;
// Generated Jun 5, 2017 11:37:11 PM by Hibernate Tools 4.3.1



/**
 * Taikhoan generated by hbm2java
 */
public class Taikhoan  implements java.io.Serializable {


     private String tenTaiKhoan;
     private String matKhau;
     private String loaiTaiKhoan;
     private String hoTen;
     private Integer namSinh;
     private String diachi;
     private String gioiTinh;

    public Taikhoan() {
    }

	
    public Taikhoan(String tenTaiKhoan) {
        this.tenTaiKhoan = tenTaiKhoan;
    }
    public Taikhoan(String tenTaiKhoan, String matKhau, String loaiTaiKhoan, String hoTen, Integer namSinh, String diachi, String gioiTinh) {
       this.tenTaiKhoan = tenTaiKhoan;
       this.matKhau = matKhau;
       this.loaiTaiKhoan = loaiTaiKhoan;
       this.hoTen = hoTen;
       this.namSinh = namSinh;
       this.diachi = diachi;
       this.gioiTinh = gioiTinh;
    }
   
    public String getTenTaiKhoan() {
        return this.tenTaiKhoan;
    }
    
    public void setTenTaiKhoan(String tenTaiKhoan) {
        this.tenTaiKhoan = tenTaiKhoan;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public String getLoaiTaiKhoan() {
        return this.loaiTaiKhoan;
    }
    
    public void setLoaiTaiKhoan(String loaiTaiKhoan) {
        this.loaiTaiKhoan = loaiTaiKhoan;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public Integer getNamSinh() {
        return this.namSinh;
    }
    
    public void setNamSinh(Integer namSinh) {
        this.namSinh = namSinh;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }




}


